Lets see if this builds a package. Might install Wordpress with it :)

diff --git a/debian/openapp-wordpress-installer.postinst b/debian/openapp-wordpress-installer.postinst
--- a/debian/openapp-wordpress-installer.postinst
+++ b/debian/openapp-wordpress-installer.postinst
@@ -18,15 +18,16 @@ set -e
 # the debian-policy package
 
 INSTALLDIR=/var/www
+TMPDIR=$(mktemp -d)
 
 fatal() {
 	echo "ERROR: $1"
-	[ -f /tmp/wordpress-$$.tar.gz ] && rm -f /tmp/wordpress-$$.tar.gz
+	[ -f ${TMPDIR}/wordpress-$$.tar.gz ] && rm -f ${TMPDIR}/wordpress-$$.tar.gz
 	exit 1
 }
 
 install_wordpress() {
-	MIRROR=http://download.openpanel.com/openapp-files/wordpress
+	MIRROR=http://wordpress.org
 	PASSWORD=`pwgen -s 10`
 
 	MYSQL=/usr/bin/mysql
@@ -39,32 +40,32 @@ install_wordpress() {
 	rm -rf /var/www
 	mkdir /var/www
 
-	[ -x /usr/bin/wget ] && wget -q -O /tmp/wordpress-$$.tar.gz ${MIRROR}/wordpress-newest.tar.gz
-	[ -f /tmp/wordpress-$$.tar.gz ] || /usr/bin/curl -s -o /tmp/wordpress-$$.tar.gz ${MIRROR}/wordpress-newest.tar.gz
+	[ -x /usr/bin/wget ] && wget -q -O ${TMPDIR}/wordpress-$$.tar.gz ${MIRROR}/latest.tar.gz
+	[ -f ${TMPDIR}/wordpress-$$.tar.gz ] || /usr/bin/curl -s -o ${TMPDIR}/wordpress-$$.tar.gz ${MIRROR}/latest.tar.gz
 	if [ $? -eq 0 ]; then
 		mkdir -p ${INSTALLDIR} || fatal "Unable to create directory ${INSTALLDIR}"
 		cd ${INSTALLDIR} || fatal "Unable to go into directory ${INSTALLDIR}"
-		tar zxf /tmp/wordpress-$$.tar.gz || fatal "Unable to extract wordpress package into ${INSTALLDIR}"
+		tar --transform 's/^wordpress/./' -zxf ${TMPDIR}/wordpress-$$.tar.gz || fatal "Unable to extract wordpress package into ${INSTALLDIR}"
 		${MYSQL} ${OPTS} -e "CREATE DATABASE wordpress CHARACTER SET utf8 COLLATE utf8_general_ci;" || fatal "Unable to create database wordpress"
 		${MYSQL} ${OPTS} -e "GRANT USAGE ON mysql.* TO 'wordpress'@'localhost' IDENTIFIED BY '$PASSWORD';" || fatal "Unable to create mysql-user wordpress"
 		${MYSQL} ${OPTS} -e "GRANT ALL PRIVILEGES ON wordpress.* to 'wordpress'@'localhost';"|| fatal "Unable to set permissions to mysql-user wordpress"
 		/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf flush-privileges || fatal "Unable to flush mysql privileges"
 
-		mv ${INSTALLDIR}/installation/configuration.php-dist ${INSTALLDIR}/configuration.php.tmp || fatal "Unable to move configuration.php to temporary file"
-		cat ${INSTALLDIR}/configuration.php.tmp | \
-		  sed -e "s#\$user = ''#\$user = 'wordpress'#" | \
-		  sed -e "s#\$password = ''#\$password = '${PASSWORD}'#" | \
-		  sed -e "s#\$db = ''#\$db = 'wordpress'#" > ${INSTALLDIR}/configuration.php
-                [ $? -eq 0 ] || fatal "Unable to prepare ${INSTALLDIR}/configuration.php"
-		cat ${INSTALLDIR}/installation/sql/mysql/wordpress.sql | sed -e 's/#__/jos_/g' | ${MYSQL} ${OPTS} wordpress || fatal "Unable to add data to the database"
-		${MYSQL} ${OPTS} wordpress -e "CREATE INDEX client_id ON jos_template_styles (client_id);"
+		mv ${INSTALLDIR}/wp-config-sample.php ${INSTALLDIR}/wp-config.php.tmp || fatal "Unable to move configuration.php to temporary file"
+		SALT=$(wget -q -O- https://api.wordpress.org/secret-key/1.1/salt/)
+		cat ${INSTALLDIR}/wp-config.php.tmp | \
+		  sed -e "s#database_name_here#wordpress#" | \
+		  sed -e "s#password_here#${PASSWORD}#" | \
+		  sed -e "s#username_here#wordpress#" | \
+		  sed -n '1h;1!H;${;g;s/\/\*\*#@+.*#@-\*\//SALTCODE/g;p;}' | \
+		  sed -e "s/SALTCODE/$( echo ${SALT} | sed -e 's/\\/\\\\/g' -e 's/\//\\\//g' -e 's/&/\\\&/g' -e 's/; define/;\\ndefine/g')/" > ${INSTALLDIR}/wp-config.php
+                [ $? -eq 0 ] || fatal "Unable to prepare ${INSTALLDIR}/wp-config.php"
 	fi
 	echo "Fixing permissions on /var/www"
 	chown -R www-data:www-data /var/www
-	chmod 640 ${INSTALLDIR}/configuration.php
-	rm -rf ${INSTALLDIR}/installation/
-	rm -f ${INSTALLDIR}/configuration.php.tmp
-	rm -f /tmp/wordpress-$$.tar.gz
+	chmod 640 ${INSTALLDIR}/wp-config.php
+	rm -f ${INSTALLDIR}/wp-config.php.tmp
+	rm -f ${TMPDIR}/wordpress-$$.tar.gz
 }
 
 case "$1" in
@@ -73,7 +74,6 @@ case "$1" in
 		echo "No old version of wordpress detected. Assuming new install"
 		install_wordpress
 		/usr/sbin/invoke-rc.d apache2 restart
-		echo "Please run openapp-wordpress-passwd if you're not installing this package in an openapp environment."
 	fi
     ;;
 
