Move openapp-backup-dismod to prerm. A deleted file causes openapp-backup-dismod to fail

diff --git a/debian/openapp-wordpress.prerm b/debian/openapp-wordpress.prerm
--- a/debian/openapp-wordpress.prerm
+++ b/debian/openapp-wordpress.prerm
@@ -1,26 +1,24 @@
 #!/bin/sh
-# postrm script for foo
+# prerm script for openpanel-openapp-mod-backup
 #
 # see: dh_installdeb(1)
 
 set -e
 
 # summary of how this script can be called:
-#        * <postrm> `remove'
-#        * <postrm> `purge'
-#        * <old-postrm> `upgrade' <new-version>
-#        * <new-postrm> `failed-upgrade' <old-version>
-#        * <new-postrm> `abort-install'
-#        * <new-postrm> `abort-install' <old-version>
-#        * <new-postrm> `abort-upgrade' <old-version>
-#        * <disappearer's-postrm> `disappear' <overwriter>
-#          <overwriter-version>
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
 
 case "$1" in
-    purge|remove|abort-install)
+    remove|deconfigure)
 		echo "Removing symlinks for openapp-backup placed by the installscript"
 		SCRIPTS="var-www home mysql openpanel wordpress"
 		BASEMODULES=/usr/lib/openapp-backup/modules
@@ -28,16 +26,15 @@ case "$1" in
 		for SCRIPT in ${SCRIPTS}; do
 			openapp-backup-dismod ${SCRIPT}
 		done
-
 		echo "Removing openapp-tuning identity-file"
 		[ -r /etc/openapp-tuning/identity ] && rm /etc/openapp-tuning/identity
     ;;
 
-    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-	;;
+    upgrade|failed-upgrade)
+    ;;
 
     *)
-        echo "postrm called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
